import { ICONS } from '../../shared/icons.mjs';
const base = '/app/dsh-for-fnos';
const $ = id => document.getElementById(id);
const registries = new Set(['https://mirrors.cloud.tencent.com/npm', 'https://registry.npmmirror.com', 'https://registry.yarnpkg.com', 'https://registry.npmjs.org']);
$('restart').innerHTML = ICONS.restart; $('open').innerHTML = ICONS.undo;
let state; let initialized = false; let submitting = false; let settingsDirty = false; let lastSnapshot = ''; let previousBusy = null; let noticeTimer;
function notice(message, error = false, duration = error ? 6500 : 3200) { clearTimeout(noticeTimer); const element = $('notice'); element.hidden = !message; element.textContent = message; element.className = error ? 'error' : ''; if (message && duration) noticeTimer = setTimeout(() => { element.hidden = true; }, duration); }
async function api(route, data) { const response = await fetch(`${base}/api/${route}`, data === undefined ? {} : { method: 'POST', headers: { 'content-type': 'application/json', 'x-fnos-request': '1' }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? '请求失败'); return result; }
function button(label, action, version) { const element = document.createElement('button'); element.textContent = label; element.disabled = !!state.busy; element.addEventListener('click', () => perform(action, { version })); return element; }
function render() {
  const label = state.busy ? `${state.busy} · ${state.current ?? ''}` : state.running ? `运行中 · ${state.current}` : state.current ? `已停止 · ${state.current}` : '未安装';
  $('runtime').textContent = label; $('runtime').className = state.busy ? 'busy' : state.running ? 'running' : '';
  $('count').textContent = `${state.versions.length} / 5`; $('market-status').textContent = state.marketInstalled ? 'dsh-market 已完成初次安装。' : '初次启动会自动安装 dsh-market；失败后可以重试。';
  document.querySelectorAll('button').forEach(x => { x.disabled = !!state.busy; }); $('open').disabled = !state.running || !!state.busy; $('restart').disabled = !state.current || !!state.busy;
  $('versions').replaceChildren(); if (!state.versions.length) { const p = document.createElement('p'); p.className = 'empty'; p.textContent = '尚未安装 DSH。首次启动会下载 latest，也可以指定版本下载。'; $('versions').append(p); }
  for (const item of state.versions) { const row = document.createElement('div'); row.className = 'version-row'; const text = document.createElement('div'); const title = document.createElement('strong'); title.textContent = item.version; const date = document.createElement('small'); date.textContent = `安装于 ${new Date(item.installedAt).toLocaleString('zh-CN')}`; text.append(title, date); row.append(text); if (item.version === state.current && state.running) { const badge = document.createElement('span'); badge.className = 'active'; badge.textContent = '正在使用'; row.append(badge); } else row.append(button('启用', 'activate', item.version)); $('versions').append(row); }
  $('releases').replaceChildren(); for (const release of state.releases) { const row = document.createElement('div'); row.className = 'release'; const text = document.createElement('span'); text.textContent = `${release.channel} · ${release.error ?? release.version}`; row.append(text); if (!release.error) { if (state.versions.some(x => x.version === release.version)) { const done = document.createElement('span'); done.textContent = '已下载'; row.append(done); } else row.append(button('下载', 'download', release.version)); } $('releases').append(row); }
  if (!initialized || !settingsDirty) { $('port').value = state.config.port; $('registry').value = registries.has(state.config.registry) ? state.config.registry : 'https://mirrors.cloud.tencent.com/npm'; document.querySelectorAll('[name=channel]').forEach(x => { x.checked = state.config.channels.includes(x.value); }); initialized = true; }
  if (state.error) notice(state.error, true); else if (previousBusy && !state.busy) notice('操作已完成。'); previousBusy = state.busy;
}
async function refresh() { const next = await api('status'); const snapshot = JSON.stringify(next); state = next; if (snapshot !== lastSnapshot) { lastSnapshot = snapshot; render(); } }
async function perform(action, data = {}) { if (submitting || state?.busy) return; submitting = true; try { await api(action, data); notice('操作已提交。'); await refresh(); } catch (error) { notice(error.message, true); } finally { submitting = false; } }
document.querySelectorAll('[data-action]').forEach(x => x.addEventListener('click', () => perform(x.dataset.action)));
$('download-form').addEventListener('submit', event => { event.preventDefault(); perform('download', { version: $('version').value.trim() }); }); $('settings-form').addEventListener('input', () => { settingsDirty = true; });
$('settings-form').addEventListener('submit', async event => { event.preventDefault(); try { await api('settings', { port: Number($('port').value), publicHost: state.config.publicHost, registry: $('registry').value, channels: ['latest', ...[...document.querySelectorAll('[name=channel]:checked')].map(x => x.value)] }); settingsDirty = false; notice('设置已保存。'); await refresh(); } catch (error) { notice(error.message, true); } });
$('open').addEventListener('click', async () => { try { const result = await api('launch', {}); location.replace(result.url); } catch (error) { notice(error.message, true); } });
await refresh().catch(error => notice(error.message, true)); setInterval(() => { if (!document.hidden) refresh().catch(error => notice(error.message, true)); }, 2500);
